Repository Electro98/cyber-growbox-2077, pull requests merged in 2021-03, with the labels that each got.

#21 :wrench: Реализованы фукции для датчика DS18B20. Closes #6
  growbox_sketch/platformio.ini
  growbox_sketch/src/sensors.cpp
  growbox_sketch/src/sensors.h
  growbox_sketch/src/setup.h
Labels: enhancement, hardware

#18 Добавлена функция TDS_Meter. Close #16
  growbox_sketch/src/Tds_Meter.cpp
Labels: hardware

#24 Была объявлена функция getLux. Update #17
  growbox_sketch/src/lightlevel.cpp
  growbox_sketch/src/sensors.cpp
  growbox_sketch/src/sensors.h
  growbox_sketch/src/setup.h
Labels: hardware, wontfix
